### PR TITLE
Categories should be sorted by "Tree" and not name

### PR DESCRIPTION
**Pull request by datune**
@see https://github.com/rainlab/blog-plugin/issues/338 and https://github.com/octobercms/october/pull/3143

### CODE REVIEW

**Comment by LukeTowers** [comment]
@datune what's the status of this?

**Comment by datune** [comment]
@LukeTowers As far as I can tell this should be the fix, I could not find anything else that could have been the cause.

**Comment by LukeTowers** [comment]
Waiting for @graker to test this then it should be good to merge.

**Comment by LukeTowers** [comment]
Thanks for your contributions @datune!

**Pull request merged**
