### PR TITLE
Add Finnish language

### PR DESCRIPTION
**Pull request by mirorauhala**
### Notes/questions
"Settings" section was hard to translate. 

#### For example:
```
This property is used by the default component partial.
```

What is a `default component partial`?

What makes a component `default`?

How is the component a `partial`?

### CODE REVIEW

**Comment by LukeTowers** [comment]
The partial is the .htm file that is the view for a component. Specifically this is talking about this file: https://github.com/rainlab/blog-plugin/blob/master/components/post/default.htm

Component partials can be overridden by themes, see http://octobercms.com/docs/cms/components#overriding-partials. Does that help answer your question?

**Comment by mirorauhala** [comment]
Ok, got it now! I was just wondering how the end-user would interpret it. That how they understand the relationship between partials and components. All components are partials, but not the other way around? Am I correct?

**Comment by LukeTowers** [comment]
Components are self contained pieces of functionality (could be thought of as building blocks) that are used on the frontend of the website. Partials are the files that are used to render a component's output (if it even has renderable output).

I would lean more towards leaving those words untranslated as they are technical terms specific to October.

**Comment by mirorauhala** [comment]
I understand your POV. Worked prev. at a localisation firm. However, I'd rather have a Finnish translation for giving a general idea of the feature for those who don't understand English than have every technical term in English. 

Having "random" words in English would make October feel unfinished and incomplete. 

PR is ready IMO.

**Comment by LukeTowers** [comment]
I'd agree with you, but if we're talking about technical terms then we should really have a glossary of established translations for them that would be used across projects that require translation (i.e. all RainLab plugins and the October core itself).

I'll merge it, but it's something to think about in the future.

**Comment by mirorauhala** [comment]
I've been thinking about that whilst translating these plugins. I'm not sure how that would be done in practice. Just a Terminology folder with bunch of markdown files for each language?

**Pull request merged**
