### PR TITLE
Added components for a post archive

### PR DESCRIPTION
**Pull request by edhardie**
...so you can show a list of past months in a sidebar and click through to posts from that month

### CODE REVIEW

**Comment by LukeTowers** [comment]
@edhardie is this something you still want in the core plugin?

**Comment by edhardie** [comment]
It would be nice @LukeTowers  - we do like to include this functionality on some of our client websites, I can imagine others wanting to do the same.  Understand this is very old though, so let me know if it needs updating to be inline with a later version of the plugin - happy to help any way I can.

**Comment by LukeTowers** [comment]
As long as it still works fully with the current version of the plugin I'm happy to include it. If you could test it with a fresh install and see if everything still works nice then let me know, that'd be great!

**Comment by LukeTowers** [comment]
You'd have to rebase it manually as well though, it's got merge conflicts with Plugin.php, lang/en/lang.php, and updates/version.yaml.

**Comment by edhardie** [comment]
hey @LukeTowers. rebased, modified slightly to work better and tested to work with build 420. Do I need to resubmit the PR? (sorry, I'm not that familiar with github)

**Comment by LukeTowers** [comment]
@edhardie at this point I'd say yeah. I'm not sure exactly what you did but your changes are completely lost in every other commit since the original request. Please resubmit it and then tag me so that I can review and merge it.

**Comment by edhardie** [comment]
Lol. Go me!

Yeah, everything looked swell on my end until I pushed it up. There's only a few files changed so I'll start again.

**Comment by LukeTowers** [comment]
Sounds good, thanks @edhardie!

**Pull request closed without merging**
