### PR TITLE
fix blogCategories component markup

### PR DESCRIPTION
**Pull request by mjauvin**
- fix link to category (was using category.url instead of category.slug)
- add hierachical url while we're at it

### CODE REVIEW

**Comment by LukeTowers** [comment]
@mjauvin that's pretty presumptuous, what was `category.url` outputting vs what you've added as your change? Who says anyone / everyone is using the URL structure you've built here?

**Comment by mjauvin** [comment]
Hey @LukeTowers it was outputting an empty string.

I was initially going to add an option for hierarchical vs flat, but since this was "broken" in the first place, it won't be a breaking change...

**Comment by mjauvin** [comment]
Basically, the link to the category was `<a href="">...`

**Comment by LukeTowers** [comment]
@mjauvin then the problem is that setUrl() is not getting called correctly: https://github.com/rainlab/blog-plugin/blob/master/models/Category.php#L89

**Comment by LukeTowers** [comment]
See https://github.com/rainlab/blog-plugin/blob/bf021dce2532dffd0f81ffd5203db2fc7ad8990d/components/Categories.php#L103 for where it should be getting called. My guess is you don't have a page setup properly for the categories, either it doesn't exist or you haven't selected it as a component property.

**Comment by LukeTowers** [comment]
Feel free to reopen if it wasn't just a misconfiguration and there is a bug here :)

**Comment by mjauvin** [comment]
Just a mis configuration, sorry. Had a momentarily brain cramp! ;)

**Comment by LukeTowers** [comment]
No worries, that's what we're here for 😄

**Pull request closed without merging**
