### PR TITLE
Add new item types (Blog post and All blog posts) for RainLab.Sitemap

### PR DESCRIPTION
**Pull request by vojtasvoboda**
Add possibility to add Blog post or All blog posts to RainLab.Sitemap:

snimek obrazovky 2016-01-06 v 16 49 28

Tested on localhost and production.

### CODE REVIEW

**Comment by daftspunk** [comment]
Seems like an odd feature, can you describe a real world example for needing this?

**Comment by vojtasvoboda** [comment]
It's request from my client to add each blog post to sitemap. It's better for faster indexing in google.com and mainly for czech search engine - seznam.cz

**Comment by vojtasvoboda** [comment]
Eventually I can make new plugin which injects this odd feature to the Blog plugin. Let me know what will be better solution.

**Comment by thewizardplusplus** [comment]
A sitemap often contains links to all posts. Especially when the site doesn't contain anything other than posts (i.e. it's only a blog).

The first comer example: the blog &mdash; https://pointersgonewild.com/, the sitemap &mdash; https://pointersgonewild.com/sitemap.xml

Please accept this pull request.

**Comment by daftspunk** [comment]
Sorry for the delay, this will be accepted. Just needs to be rebased.

**Comment by vojtasvoboda** [comment]
PR rebased and withou conflict

**Comment by thewizardplusplus** [comment]
@vojtasvoboda, thank you very much!

@daftspunk, please, merge it.

**Comment by thewizardplusplus** [comment]
@daftspunk, thank you very much!

**Pull request merged**
