### PR TITLE
Consistent isPublished scope from Post and Category empty check

### PR DESCRIPTION
**Pull request by Wadeck**
Use same condition to know if a post is publish as in the scope "isPublished" from Post.

### CODE REVIEW

**Comment by LukeTowers** [comment]
What problem / issue is this solving?

**Comment by Wadeck** [comment]
When you have categories that have posts published but in the future, they
are displayed but with a counter to 0. It's only occurring when you enable
displayEmpty.

**Comment by LukeTowers** [comment]
@Wadeck does this still need to be fixed?

**Comment by Wadeck** [comment]
@LukeTowers will take a look again as soon as I find time, probably this week-end

**Comment by Wadeck** [comment]
@LukeTowers so after testing again, it seems to be still there.

It's not a critical issue, only concerning people that use a "counter" of published post AND publish in advance the blog posts AND have enable the displayEmpty option.

**Comment by Wadeck** [comment]
Thank you @LukeTowers  👍

**Comment by LukeTowers** [comment]
No problem @Wadeck, thanks for submitting the fix!

**Pull request merged**
