### PR TITLE
Add front-end preview for authorized backend admin

### PR DESCRIPTION
**Pull request by pvullioud**
https://github.com/rainlab/blog-plugin/issues/193

### CODE REVIEW

**Comment by pvullioud** [comment]
Done, tabs replaced by spaces

**Comment by daftspunk** [comment]
This is a good feature, I'll fix it up. Please shoot for 4 spaces next time! =)

**Comment by pvullioud** [comment]
now psr-1 / 2 style is my default for october :)

**Comment by daftspunk** [comment]
Thanks.

I wonder if this feature might be misleading for users who are uninformed about the logic?

For example, I forget to tick "Published" on my blog post and I assume it is published because I see it on the front-end, then I go bed. Next day I find out it was never published, oops.

**Comment by pvullioud** [comment]
Other CMS use an add a locker icon in front. Could be a easy solution

**Comment by daftspunk** [comment]
So, you're saying prepend the title attribute of the blog post with a 🔒 character? When unpublished and viewing as an admin.

**Comment by pvullioud** [comment]
Yes, in both list and detail with a tooltips.

**Comment by daftspunk** [comment]
Literally thinking of this in the component...

```
// If conditions met
$post->title = '🔒 ' . $post->title;
```

**Comment by pvullioud** [comment]
yes with a tool tips

**Comment by daftspunk** [comment]
The lock would be enough to be a trigger for the editor, I think. Including the lock character is cheeky, injecting HTML is dirty -- since the attribute will most likely be escaped by Twig.

**Comment by pvullioud** [comment]
We can start with a lock. It should be clear enough. It's a well know symbol in CMS world for access restriction.

**Comment by therealkevinard** [comment]
Does this PR affect `$this->post` in the page context? 
Consider this page: 
https://therealkevinard.com/article/processing-raw-google-analytics-data-with-elastic-stack-part-1-getting-raw-data
I'm using a common page with the post component dropped in, and the old `$this->page->title=$this->post->title` for changing the default title from "Single" to whatever the post title is. 
I noticed late last night that the post title isn't coming through, and a quick peek shows `$this->post=null`
Granted, I did a few other light things yesterday, but the most significant was switching the plugin to this branch. 
I didn't notice it at first, or rather, I noticed it but chalked it up to me viewing an unpublished post (ref my pr at https://github.com/anand-patel/oc-seo-extension/issues/35), but last night I realized it was blog-wide.

**Comment by pvullioud** [comment]
@therealkevinard as you can see in the diff : https://github.com/rainlab/blog-plugin/pull/316/files
`$this->post` is not affected by this PR.

**Comment by LukeTowers** [comment]
@therealkevinard you're looking for issue #326

**Pull request merged**
