### PR TITLE
Use where() instead of whereDate()

### PR DESCRIPTION
**Pull request by lthurston**
Associated with issue #390

### CODE REVIEW

**Comment by LukeTowers** [comment]
Thanks @lthurston!

**Comment by nizzac** [comment]
Should this change be in the released version when I do php artisan plugin:install Rainlab.Blog because I'm not getting it. But i am getting version 1.2.19 of the plugin.

**Comment by LukeTowers** [comment]
@nizzac updates were marked as pending, which requires enableEdgeUpdates in the config/cms.php to be enabled. I've marked the updates as stable, so you should be able to download them now.

**Comment by nizzac** [comment]
Perfect. Thank you!

**Pull request merged**
